name: axe-core
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  axe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:3000/index.html
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          npm install -g chromedriver@118 --chromedriver-force-download
          axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://localhost:3000/index.html --exit